<font size=5>KFold Cross Validation</font>

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [5]:
from sklearn.model_selection import train_test_split
A_train,a_test,B_train,b_test = train_test_split(digits.data,digits.target,test_size=0.3)

<font size=3>Logistic Regression</font>

In [6]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(A_train,B_train)
lr.score(a_test,b_test)

0.9537037037037037

SVM

In [7]:
svm = SVC(gamma='auto')
svm.fit(A_train,B_train)
svm.score(a_test,b_test)

0.4888888888888889

Random Forest

In [8]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(A_train,B_train)
rf.score(a_test,b_test)

0.975925925925926

<font size=5>KFold Cross Validation</font>
<br>
Basic eg:

In [9]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


Use Kfold for our digits eg:

In [11]:
def get_score(model,A_train,a_test,B_train,b_test):
 model.fit(A_train,B_train)
 return model.score(a_test,b_test)

In [12]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [13]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [14]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [15]:
scores_rf

[0.9265442404006677, 0.9565943238731218, 0.9265442404006677]

cross_val_score function

In [16]:
from sklearn.model_selection import cross_val_score

Logistic regression model performance using cross_val_score

In [17]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data,digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

svm model performance using cross_val_score

In [18]:
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

random forest performance using cross_val_score

In [19]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=3)

array([0.93155259, 0.95993322, 0.92654424])

Parameter tunning using k fold cross validation

In [21]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8758814400993172